config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'static_pages#top'
  get '/signup', to: 'users#new'
  
  # ログイン機能
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :bases
  resources :users do
    collection { post :import }
    collection { get :go_work }
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      get 'attendances/working'
      get 'attendances/request_overtime'
      patch 'attendances/update_overtime'
    end
    
      
    resources :attendances, only: :update
    end
  
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  # 「remember_token」という仮想の属性を作成する。
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: true
  validates :department, length: { in: 2..30 }, allow_blank: true
  validates :basic_time, presence: true
  validates :work_time, presence: true
  # bcrypt gemを追加したことで、has_secure_passwordを使用することができるようになった。 
  has_secure_password 
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  
  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost =
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end
  
  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # 永続セッションのためハッシュ化したトークンをデータベースに記憶する。
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # トークンがダイジェストと一致すればtrueを返す。
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  # ユーザーのログイン情報を破棄します。
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  # あいまい検索　#{search}の値を含む検索があれば表示、なければ全表示
  def self.search(search)
    if search
      User.where(['name LIKE ?', "%#{search}%"])
    else
      User.all
    end
  end
  
  #csvファイルの内容をDBに登録する
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      user = find_by(id: row["id"]) || new
      # CSVからデータを取得し、設定する
      user.attributes = row.to_hash.slice(*updatable_attributes)
      # 保存する
      user.save!(validate: false)
      end
  end


  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["name", "email", "department", "employee_number", "uid", "basic_work_time", 
      "designated_work_start_time", "designated_work_end_time", "superior", "admin", "password"]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :set_user, only: [:show, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :logged_in_user, only: [:show, :edit, :update, :index, :destroy, :edit_basic_info, :update_basic_info]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user,only: [:index, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  # before_action :correct_user_or_admin_user ,only: :show
  before_action :set_one_month, only: :show

  def new
    @user = User.new
  end

  def show
    @worked_sum = @attendances.where.not(started_at: nil).count
  end

  def index
    @users = User.search(params[:search]).paginate(page: params[:page])
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      flash[:success] = "新規作成に成功しました。"
      redirect_to @user
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @user.update_attributes(user_params)
      flash[:success] = "更新に成功しました。"
      redirect_to users_url @user
    else
      @users = User.search(params[:search]).paginate(page: params[:page])
      render :index
      # flash[:danger] = "更新に失敗しました。"
      # redirect_to users_url @user
    end
  end
  
  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_path
  end
  
  def edit_basic_info
  end
  
  def update_basic_info
    @users = User.all
    @users.each do |user|
      if user.update_attributes(basic_info_params)
        flash[:success] = "基本情報の更新に成功しました。"
      else
        flash[:danger] = "更新に失敗しました。<br>" + @user.errors.full_messages.join("<br>")
      end
    end
    redirect_to user_path(current_user)
  end

  def go_work
    @users = User.all.includes(:attendances)
  end

  def import
    if params[:file].blank?
      flash[:danger] = "読み込むCSVファイルを選択して下さい。"
      redirect_to users_url
    elsif File.extname(params[:file].original_filename) != ".csv"
      flash[:danger] = "CSVファイルのみ読み込み可能です。"
      redirect_to users_url
    else
      if User.all.include?(params[:file])
        flash[:success] = "登録済みユーザーがいます。"
      　redirect_to users_url
      else
      User.import(params[:file])
        flash[:success] = "ユーザーをインポートしました。"
        redirect_to users_url
      end
    end
  end
  
  # def import
    # result = User.import(params[:file])
    # f_message = User.import_result(result)
    # flash[f_message[:status]] = f_message[:message]
    # redirect_to users_url
  # end
  
  private
  
    def user_params
      params.require(:user).permit(:name, :email, :department, :password,
                                   :password_confirmation, :employee_number, 
                                   :uid, :basic_work_time, :designated_work_start_time,
                                   :designated_work_end_time)
    end
    
    def basic_info_params
      params.require(:user).permit(:department, :basic_time, :work_time)
    end
    
    
end

app/helpers/users_helper.rb
module UsersHelper
  
  # 勤怠基本情報を指定のフォーマットで返します。
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
end

app/views/users/_edit_basic_info.html.erb
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '更新') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
      <h1 class="modal-title">基本情報編集</h1>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true, method: :patch) do |f| %>
            <%= render 'shared/error_messages', object: @user %>

            <%= f.label :name, class: "label-#{yield(:class_text)}" %>
            <p><%= @user.name %></p>

            <%= f.label :basic_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :basic_time, class: "form-control" %>

            <%= f.label :work_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :work_time, class: "form-control" %>

            <div class="center">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages' %>
    
  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>
  
  <%= f.label :department, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :department, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit "#{yield(:btn_text)}", class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/_user.html.erb
<% provide(:class_text, "user-edit") %>
<% provide(:btn_text, "編集する") %>
  <%= form_with(model: user, url: user_url(user), local: true) do |f| %>
  <%= render 'shared/error_messages', { user: user } %>
   

    
  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>
  
  <%= f.label :department, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :department, class: "form-control" %>

  <%= f.label :employee_number, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :employee_number, class: "form-control" %>

  <%= f.label :uid, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :uid, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>
  
  <%= f.label :basic_work_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :basic_work_time, class: "form-control" %>
  
  <%= f.label :designated_work_start_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :designated_work_start_time, class: "form-control" %>

  <%= f.label :designated_work_end_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :designated_work_end_time, class: "form-control" %>

  <%= f.submit "#{yield(:btn_text)}", class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, @user.name + "の更新") %>
<% provide(:class_text, "user-edit") %>
<% provide(:btn_text, "更新") %>
<h1>アカウント情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit_basic_info.js.erb
$("#edit-basic-info").html("<%= escape_javascript(render 'edit_basic_info') %>");
$("#edit-basic-info").modal("show");

app/views/users/go_work.html.erb
<% provide(:title, "出勤中社員一覧") %>
<div>
  <h1>出勤中社員一覧</h1>
  <table class="table table-bordered table-condensed table-hover" id="table-attendances">
    <thead>
      <tr>
        <th>社員番号</th>
        <th>名前</th>
        
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <% user.attendances.each do |attendance| %>
          <% if attendance.worked_on == Date.current &&
                attendance.started_at != nil
                attendance.finished_at == nil %>
      <tr>
        <td><%= user.employee_number %></td>
        <td><%= user.name %></td>
      </tr>
      <% end %>
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/index.html.erb
<% provide(:title, "ユーザー一覧") %>
<% if params[:search].blank? %>
  <h1>ユーザー一覧</h1>
  <% else %>
  <h1>検索結果</h1>
<% end %>

<P>ユーザー検索</P>
<%= form_tag users_path, method: :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "search", name: nil %>
  </p>
<% end %>
<!--ローカルファイルからユーザー情報を追加-->
<%= form_tag import_users_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "CSVをインポート", class:"btn btn-primary" %>
<% end %>
<!--アコーディオン表示-->
<table class="table table-concerned table-hover">
  <% @users.each do |user| %>
  <tr>
    <td class="col-md-10 col-md-offset-1">
      <% if current_user.admin? && !current_user?(user) %>
      <%= user.name %><br>
      <%= link_to "削除", user, method: :delete,
                          data: { confirm: "削除してよろしいですか？" },
                          class: "btn btn-primary btn-default" %><br>
      <div class="panel-group">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <button type="button" data-toggle="collapse" data-target="#collapse<%= user.id %>" class="btn btn-primary btn-lg">編集</button>
            </h4>
          </div>
          <div id="collapse<%= user.id %>" class="panel-collapse collapse">
            <div class="panel-body"><%= render 'user', { user: user } %></div>
          </div>
        </div>
        <% end %>
      </div>
    </td>
  </tr>
  <% end %>
</table>
<%= will_paginate %>

<!--モーダルウインドウ表示-->
<!--下に記述してあるコードは勤怠チュートリアルの名残。勤怠Aでは使用しない。-->
<!--<div id="edit-basic-info" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>-->

app/views/users/new.html.erb
<% provide(:title, "アカウント作成") %>
<% provide(:class_text, "signup") %>
<% provide(:btn_text, "新規作成") %>
<h1>アカウント作成</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div>
  <table class="table table-bordered table-sm user-table">
    <tr>
      <td>
        <%= link_to "◁",user_path(date: @first_day.prev_month),class: "btn btn-info" %>
        【<%= l(@first_day, format: :middle) %>】時間管理表
        <%= link_to "▷",user_path(date: @first_day.next_month),class: "btn btn-info" %>
        </td>
      <td>指定勤務開始時間:<%= format_basic_info(@user.work_time) %></td>
      <td colspan="3">基本時間:<%= format_basic_info(@user.basic_time) %></td>
      <td>初日:<%= l(@first_day, format: :short) %></td>
    </tr>
    <tr>
      <td>所属:<%= @user.department.present? ? @user.department : "未所属" %></td>
      <td>氏名:<%= @user.name %></td>
      <td>コード</td>
      <td>#</td>
      <td>出勤日数:<%= @worked_sum %>日</td>
      <td>締め:<%= l(@last_day, format: :short) %></td>
    </tr>
  </table>
</div>

<div>
  <div><%= link_to "【所属長承認申請のお知らせ】2件通知があります", "#", class: "text-danger" %></div>
  <div><%= link_to "【勤怠変更申請のお知らせ】2件通知があります", "#", class: "text-danger" %></div>
  <div><%= link_to "【残業申請のお知らせ】2件通知があります", "#", class: "text-danger" %></div>
  <div>
    <%= link_to "勤怠を編集", attendances_edit_one_month_user_path(date: @first_day),
      class: "btn btn-primary" %>
    <%= link_to "CSV出力", "#", class: "btn btn-primary" %>
  </div>
  <div>
    <%= link_to "勤怠修正ログ（承認済）", "#", class: "btn btn-primary" %>
  </div>
  <table class="table table-bordered table-sm table-hover" id="table-attendances">
    <thead>
      
      <tr>
        <th rowspan="2"></th>
        <th rowspan="3">日付</th>
        <th rowspan="3">曜日</th>
        <th colspan="8">【実績】</th>
        <th colspan="5">所定外勤務</th>
      </tr>
      <tr>
        <th colspan="3">出社</th>
        <th colspan="3">退社</th>
        <th rowspan="2">在社時間</th>
        <th rowspan="2">備考</th>
        <th colspan="2">終了予定時間</th>
        <th rowspan="2">時間外時間</th>
        <th rowspan="2">業務処理内容</th>
        <th rowspan="2">指示者確認㊞</th>
      </tr>
      <tr>
        <th>残業申請</th>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
      </tr>
    </thead>
    
    <tbody>
      <% @attendances.each do |day| %>
      <% css_class = case %w{日 月 火 水 木 金 土}[day.worked_on.wday]
        when '土'
        'text-primary'
        when '日'
        'text-danger' end %>
      <tr>
        <!--残業申請ボタン-->
        <td>    
          <%= link_to "残業申請", attendances_request_overtime_user_path(date: day.worked_on), class: "btn btn-primary" %>
        </td>
        <td><%= l(day.worked_on,format: :short) %></td>
        <td class="<%= css_class %>"><%=$days_of_the_week[day.worked_on.wday] %></td>
        <td><%= l(day.started_at, format: :hour) if day.started_at.present? %></td>
          <td><%= l(day.started_at.floor_to(15.minutes), format: :minutes) if day.started_at.present? %></td>
        <td><% if btn_text = attendance_state(day) %>
            <%= link_to "#{ btn_text }", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-attendance" %>
          <% end %>
        </td>
        <td><%= l(day.finished_at, format: :hour) if day.finished_at.present? %></td>
        <td><%= l(day.finished_at.floor_to(15.minutes), format: :minutes) if day.finished_at.present? %></td>
        <td></td>
        <td>
          <% if day.started_at.present? && day.finished_at.present? %>
          <%= str_times = working_times(day.started_at.floor_to(15.minutes), day.finished_at.floor_to(15.minutes)) %>
          <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
          <% end %>
        </td>
        <td><%= day.note %></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <td></td>
        <td colspan="2"></td>
        <td colspan="6"></td>
        <td colspan="1"><%= format("%.2f", @total_working_times.to_f) %></td>
        <td colspan="5"></td>
        <td>所属長承認㊞
          <br>
        <%= form_with(model: @user, local:true) do |f| %>
          <%= f.select :user_id, [['上長A', 1], ['上長B', 2]], { include_blank: true, selected: 1 }, { id: "user_id", class: "user_class" } %>
        <% end %>
        </td>
      </tr>
    </tfoot>
  </table>
</div>