config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'static_pages#top'
  get '/signup', to: 'users#new'
  
  # ログイン機能
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :bases
  resources :users do
    collection { post :import }
    collection { get :go_work }
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      get 'attendances/working'
      get 'attendances/request_overtime'
      patch 'attendances/update_overtime'
    end
    
      
    resources :attendances, only: :update
    end
  
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  
  validates :worked_on, presence: true
  validates :note, length: { maximum: 50 }
  validates :scheduled_end_time, presence: true
  validates :business_processing, presence: true
  validates :overtime_boss, presence: true
  
  # 出勤時間が存在しない場合、退勤時間は無効
  validate :finished_at_is_invalid_wihout_started_at
  
  # 退勤時間が存在しない場合、出勤時間は無効
  validate :started_at_is_invalid_wihout_finished_at, on: :only_update_month
  
  # 出勤時間、退勤時間ともに存在する時、出勤時間より早い退勤時間は無効
  validate :started_at_than_finished_at_fast_if_invalid
  
  
  def finished_at_is_invalid_wihout_started_at
    errors.add(:started_at, "が必要ですyo。") if started_at.blank? && finished_at.present?
  end
  
  def started_at_is_invalid_wihout_finished_at
    errors.add(:finished_at, "が必要です。") if finished_at.blank? && started_at.present?
  end
  
  def started_at_than_finished_at_fast_if_invalid
    if started_at.present? && finished_at.present?
      errors.add(:started_at, "より早い退勤時間は無効です") if started_at > finished_at
    end
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_user, only: [:edit_one_month, :update_one_month, :working]
  before_action :logged_in_user, only: [:update, :edit_one_month, :working]
  before_action :admin_or_correct_user, only: [:update, :edit_one_month, :update_one_month, :working]
  before_action :set_one_month, only: :edit_one_month
  UPDATE_ERROR_MSG = "勤怠登録に失敗しました。やり直して下さい。"
  def update
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:id])
    if @attendance.started_at.nil?
      if @attendance.update_attributes(started_at: Time.current.change(sec: 0))
        flash[:success] = "おはようございます！"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
      
    elsif @attendance.finished_at.nil?
      if @attendance.update_attributes(finished_at: Time.current.change(sec: 0))
        flash[:success] = "お疲れ様でした！"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    end
    redirect_to user_url @user
  end
  
  def edit_one_month
  end
  
  def update_one_month
    ActiveRecord::Base.transaction do #トランザクションを開始します
      attendances_params.each do |id, item|
        attendance = Attendance.find(id)
        attendance.assign_attributes(item)
        attendance.save!(context: :only_update_month)
      end
    end
      flash[:success] = "1ヶ月分の勤怠情報を更新しました。"
      redirect_to user_url(date: params[:date])
  rescue ActiveRecord::RecordInvalid #トランザクションによるエラーの分岐です
    flash[:danger] = "無効な入力データがあった為、更新をキャンセルしました"
    redirect_to attendances_edit_one_month_user_url(date: params[:date])
  end
  
  def request_overtime
    @user = User.find(params[:id])
    @attendance = Attendance.find_by(worked_on: params[:date])
    @attendances = @user.attendances.where(worked_on: @attendance.worked_on)
  end
  
  def update_overtime
    ActiveRecord::Base.transaction do
      request_params.each do |id, item|
        attendance = Attendance.find(id)
        attendance.update_attributes!(item)
      end
    end
    flash[:success] = "残業申請を受け付けました。"
    redirect_to user_url(date:params[:date])
  rescue ActiveRecord::RecordInvalid # トランザクションによるエラーの分岐です。
  flash[:danger] = "無効な入力データがあった為、申請をキャンセルしました。"
  redirect_to user_url(date:params[:date])
  end
  
  # def working
    # @users = User.all.includes(:attendances)
    # @in_attendances = Attendance.where(worked_on: Date.current)
                                # .where(finished_at: nil)
                                # .where.not(started_at: nil)
                                # .includes(:user)
  # end

  private
  
  def attendances_params
    params.require(:user).permit(attendances: [:started_at, :finished_at, :note])[:attendances]
  end
  
  def request_params
    params.require(:user).permit(attendances: [:overtime_request_status, :scheduled_end_time, :overnight, :business_processing, :overtime_boss])[:attendances]
  end
  
  # beforeフィルター
  # 管理権限者、または現在ログインしているユーザーを許可します。
  def admin_or_correct_user
    @user = User.find(params[:user_id]) if @user.blank?
    unless current_user?(@user) || current_user.admin?
      flash[:danger] = "編集権限がありません。"
      redirect_to root_url
    end
  end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
  def attendance_state(attendance)
    if Date.current == attendance.worked_on
      return '出勤' if attendance.started_at.nil?
      return '退勤' if attendance.started_at.present? && attendance.finished_at.nil?
    end
    return false
  end
  
  def working_times(start, finish)
    format("%.2f", (((finish - start) / 60) / 60.0))
  end
  
  def format_hour(time)
    format("%.d", ((time.hour)))
  end
  
  def format_min(time)
    format("%.2d", ((time.min) ))
  end
    
end

app/views/attendances/edit_one_month.html.erb
<% provide(:title, @user.name) %>
<%= form_with(model: @user, url:attendances_update_one_month_user_path(date: @first_day),local: true, method: :patch) do |f| %>
<div>
  <h1>勤怠編集画面</h1>
  <table class="table table-bordered table-condensed table-hover" id="table-attendances">
    <thead>
      <tr>
        <th>日付</th>
        <th>曜日</th>
        <th>出社</th>
        <th>退社</th>
        <th>翌日</th>
        <th>在社時間</th>
        <th>備考</th>
        <th>指示者確認</th>
      </tr>
    </thead>
    <tbody>
      <% @attendances.each do |day| %>
        <%= f.fields_for "attendances[]",day do |attendance| %>
        <tr>
          <!--日付-->
          <td><%= l(day.worked_on, format: :short) %></td>
          <!--曜日-->
          <td><%= $days_of_the_week[day.worked_on.wday] %></td>
          <!--管理者、それ以外ともに当日より未来の勤怠情報編集不可-->
          <% if (Date.current < day.worked_on) %>
          <td><%= attendance.time_field :started_at, readonly: true, class: "form-control" %></td>
          <td><%= attendance.time_field :finished_at, readonly: true, class: "form-control" %></td>
          <% else %>
          <td><%= attendance.time_field :started_at, class: "form-control" %></td>
          <td><%= attendance.time_field :finished_at, class: "form-control" %></td>
          <% end %>
          <td></td>
          <td>
            <% if day.started_at.present? && day.finished_at.present? %>
              <%= working_times(day.started_at, day.finished_at) %>
            <% end %>
          </td>
          
          <td>
            <!--管理者、それ以外ともに当日より未来の勤怠情報編集不可-->
            <% if (Date.current < day.worked_on) %>
            <%= attendance.text_field :note, readonly: true, class: "form-control" %>
            <% else %>
            <%= attendance.text_field :note, class: "form-control" %>
            <% end %>
          </td>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>
<div class="center">
  <%= f.submit "まとめて更新", class:"btn btn-lg btn-primary" %>
  <%= link_to "キャンセル", user_path(date: @first_day), class: "btn btn-lg btn-default" %>
</div>
<% end %>

app/views/attendances/request_overtime.html.erb
<% provide(:title, @user.name) %>
<h1>【残業申請】</h1>
  <%= form_with(model: @user, url: attendances_update_overtime_user_path, local: true, method: :patch) do |f| %>
    <table class="table table-bordered table-condensed table-hover">
      <thead>
        <tr>
          <th>日付</th>
          <th>曜日</th>
          <th>終了予定時間</th>
          <th>翌日</th>
          <th>業務処理内容</th>
          <th>指示者確認</th>
        </tr>
      </thead>
      
      <tbody>
        <% @attendances.each do |day| %>
          <% 
            css_class = 
            case %w{日 月 火 水 木 金 土}[day.worked_on.wday]
            when '土'
              'text-primary'
            when '日'
              'text-danger'
            end 
          %>
          <%= f.fields_for "attendances[]",day do |attendance| %>
            <%= attendance.hidden_field :overtime_request_status, value: "申請中" %>
            <tr>
              <td><%= l(@attendance.worked_on, format: :short, class: 'hizuke') %></td>
              <td><%= $days_of_the_week[day.worked_on.wday] %></td>
              <td><%= attendance.time_field :scheduled_end_time, class: "form-control" %></td>
              <td><%= attendance.check_box :overnight, id: "overnight" %></td>
              <td><%= attendance.text_field :business_processing, class: "form-control" %></td>
              <!--selectを使ってる。最終的にはcllection_selectに作り変えたい-->
              <td>
                <%= 
                  attendance.select :overtime_boss, 
                 {'上長A': 1, '上長B': 2},
                  { include_blank: true },
                  { class: 'form-control' , required: true }
                %> 
              </td>
            </tr>
            <% end %>
          <% end %>
      </tbody>
    </table>
    <div class="center">
      <%= f.submit "変更を送信する", class:"btn btn-lg btn-block btn-primary" %>
    </div>
  <% end %>
  

app/views/attendances/working.html.erb
<% provide(:title, "出勤中社員一覧") %>
<div>
  <h1>出勤中社員一覧</h1>
  <table class="table table-bordered table-condensed table-hover" id="table-attendances">
    <thead>
      <tr>
        <th>社員番号</th>
        <th>名前</th>
        
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <% user.attendances.each do |attendance| %>
      <% if attendance.started_at.present? && attendance.finished_at.nil? %>
        <tr>
          <td><%= user.employee_number %></td>
          <td><%= user.name %></td>
        </tr>
      <% end %>
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>